### PR TITLE
Migrate to Xcode 11.1 so that the iOS 13 SDK may be used.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
Not sure about the cadence of toolchain rolls in g3. This may have consequence for local engine builds in that environment.

**Comment by dnfield** [comment]
Can we roll to any earlier version?  This will push up requirements for bitcode.  We should also verify what toolchain is being used in google3

**Comment by chinmaygarde** [comment]
> Can we roll to any earlier version?

11.0 I suppose but that still pushes up the bitcode requirement. I thought the guidance w.r.t bitcode was "use the latest Xcode". Per that, this should version bump should be within reason right?

> We should also verify what toolchain is being used in google3

Yeah, I need to figure out how to tell this is fine in g3. I see you have attempted such a roll in the past, how did you verify?

**Comment by dnfield** [comment]
As I recall it broke on the bots

**Comment by chinmaygarde** [comment]
xref [b/141132595](b/141132595)

**Comment by chinmaygarde** [comment]
> As I recall it broke on the bots

Which ones? The rolls into g3 are manual.

**Comment by dnfield** [comment]
Devicelab.  We need to make sure it's up to date with at least this version of Xcode.

/cc @digiter

**Comment by dnfield** [comment]
(And Cirrus, but that should be easy enough to update)

**Comment by chinmaygarde** [comment]
We don't have any Mac presubmits on Cirrus though right?

**Comment by cbracken** [comment]
@dnfield context is https://github.com/flutter/flutter/issues/40198 which requires us to bump to a minimum of Xcode 11. Do we have evidence that 11.1 has any additional implications re: Bitcode vs Xcode 11?

**Comment by cbracken** [comment]
In terms of co-ordination with the device lab, I was planning to put together an Xcode 11 roll across the board tomorrow. @chinmaygarde did you want to take  look at that earlier or shall I hit everything up at once tomorrow?

**Comment by chinmaygarde** [comment]
I don't think I will be able to get to this today. So go ahead. This update has a few more steps than I initially anticipated. Taking notes here [go/flutter-xcode-update-checklist](go/flutter-xcode-update-checklist). Feel free to add instructions to it as necessary. Still figuring out how to reconcile the toolchain in Google3 ATM.

**Comment by cbracken** [comment]
SGTM! I'll check on 11.1 internally and see if I can detect any bitcode differences. If we're good to go with 11.1 I'll kick off the upgrade in the devicelab and merge this PR tomorrow.

**Comment by dnfield** [comment]
@cbracken just that customers will be required to use at least 11.1

**Comment by brandondiamond** [comment]
Hey @cbracken -- just wanted to see if this is okay to merge. (I'm hoping to get some related changes merged early this week and would be super grateful for your help!)

**Comment by dnfield** [comment]
I think this should wait until the devicelab is updated to Xcode 11.1

@digiter should know the status of that.  I don't fully understand the priority of what this unblocks though - if there's some critiical issue this resolves, we could look into working around whatever issues it would cause for the present devicelab setup.  I suspect the devicelab will be ready soon though, since I see the new hardware sitting on @digiter's desk :)

**Comment by brandondiamond** [comment]
Ah, got it -- thanks for the background!

I've got a couple of PRs that address a fidelity issue in cupertino (in particular, I'm adding support for a new switch label accessibility flag in iOS 13). The associated engine change is flutter/engine#12467.

Needless to say, these aren't high pri :) Just hoping to get them merged before our triage meeting on Friday.

cc @johnsonmh

**Comment by cbracken** [comment]
Correct - this needs to wait for devicelab upgrades. I expect to find time to do that sometime around Thu/Fri this week (next couple days are chewed up with meetings).

**Comment by digiter** [comment]
@cbracken I'm working the upgrades right now, please see flutter/flutter#39921

So the conclusion is we want to upgrade to 11.1?

**Comment by cbracken** [comment]
@digiter we need to do some digging to check internal Xcode version availability. Xcode 11 is definitely doable and solves the App Store requirement. I'd probably lean that way as opposed to 11.1.

**Comment by chinmaygarde** [comment]
@cbracken I have updated it to 11.0 instead of 11.1. PTAL.

**Comment by cbracken** [comment]
re-lgtm but please wait to land until the devicelab upgrades are landed. This morning the devicelab, particularly the mac bots, were not in a happy place.

**Comment by brandondiamond** [comment]
Hey @cbracken! Just wanted to check-in to see if there's any news on the devicelab updates (once this PR is merged, I'll be able to merge a bunch of work related to adding accessibility labels to CupertinoSwitch). Thanks :)

**Comment by digiter** [comment]
> Hey @cbracken! Just wanted to check-in to see if there's any news on the devicelab updates (once this PR is merged, I'll be able to merge a bunch of work related to adding accessibility labels to CupertinoSwitch). Thanks :)

See flutter/flutter#39921

**Comment by digiter** [comment]
Mac machines in devicelab are using Xcode 11.0 now.

**Comment by chinmaygarde** [comment]
> Mac machines in devicelab are using Xcode 11.0 now.

Thanks. Landing this update.

**Comment by chinmaygarde** [comment]
Reverting [because gem installation failure](https://github.com/flutter/infra/pull/67).

**Comment by theneshofficial** [comment]
Any updates on this migration?

**Pull request merged**
