### PR TITLE
[fuchsia_ctl] Update version to 0.0.17

### PR DESCRIPTION
**Pull request by iskakaushik**

### CODE REVIEW

**Comment by godofredoc** [comment]
Can we try the new version with a led execution?

led get-builder 'luci.flutter.prod:Linux Fuchsia' | led edit -p fuchsia_ctl_version="version:0.0.17" | led launch

**Comment by dnfield** [comment]
+1 on @godofredoc and it would be extra nice to link to the swarming task here.

**Comment by iskakaushik** [comment]
I triggered it a while ago here the run: https://chromium-swarm.appspot.com/task?id=4a0c9b261b914a10

**Comment by dnfield** [comment]
Can you trigger the Engine one as well?

**Comment by godofredoc** [comment]
Sorry I didn't see Dan's request, before sending the +2

**Comment by iskakaushik** [comment]
https://ci.chromium.org/raw/build/logs.chromium.org/flutter/led/kaushikiska_google.com/cc9a2cd787174fe4ed19b959734bce5e7c942b77e70b790327423f633a1dcf14/+/annotations?server=chromium-swarm.appspot.com

**Comment by iskakaushik** [comment]
:crossed_fingers: hoping it will pass. Will merge when its green.

**Pull request merged**
