### PR TITLE
Add flutter sdk drone configurations.

### PR DESCRIPTION
**Pull request by godofredoc**
This will enable the drone builder in buildbucket to be able to test the
final recipe.

Bug:
  https://github.com/flutter/flutter/issues/62811

### CODE REVIEW

**Comment by christopherfujino** [comment]
@godofredoc validation errors

**Comment by christopherfujino** [comment]
So the idea is the `flutter/flutter` recipe will spawn builds of `flutter/flutter_drone`?

**Comment by godofredoc** [comment]
> @godofredoc validation errors

fixed

**Comment by godofredoc** [comment]
> So the idea is a single `flutter/flutter` build will spawn (and collect) multiple builds of `flutter/flutter_drone`?

Yes, from the dashboard point of view we'll have a single framework_test but the build will spawn 4 drones to run the tests. This way on high availability of bots the test will complete in a fraction of time.

**Pull request merged**
