### PR TITLE
turned on flutter_engine_group_performance.dart

### PR DESCRIPTION
**Pull request by gaaclarke**
issue: https://github.com/flutter/flutter/issues/72026

depends on: https://github.com/flutter/flutter/pull/75374

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by gaaclarke** [comment]
What's the best way to babysit this to make sure it landed well, since a successful local run doesn't seem to guarantee it will run successfully on the bots?

**Comment by gaaclarke** [comment]
I suspect results should be showing up at https://flutter-flutter-perf.skia.org/e/?queries=test%3Dflutter_engine_group_performance

**Comment by keyonghan** [comment]
Before enabling it in flutter-dashboard, milo dashboard is where we check running status: https://ci.chromium.org/p/flutter/g/devicelab/console

**Pull request merged**
