### PR TITLE
Use only 12 core macs in tool integration tests.

### PR DESCRIPTION
**Pull request by godofredoc**
Using 4 core vms have been causing those tests to fail consistently.

Bug: https://github.com/flutter/flutter/issues/81793

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
LGTM

**Comment by keyonghan** [comment]
Shall we make it the same for try builders?

**Comment by godofredoc** [comment]
Let me check if the try pool has 4 core machines

**Comment by godofredoc** [comment]
> Let me check if the try pool has 4 core machines

Actually not needed we only have 12 core machines in the try pool.

**Pull request merged**
