### PR TITLE
Add cocoapod configurations.

### PR DESCRIPTION
**Pull request by godofredoc**
It also removes several properties not being used.

Bug:
  https://github.com/flutter/flutter/issues/65223

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
LGTM

**Review by christopherfujino — COMMENTED** [review]
Should we use a gemfile? (this comment should have been on the recipe CL, but I just thought of it now). With rubygems, if you don't have a `gemfile.lock` file, transitive deps can change, and this broke us once with `fastlane`.

**Comment by godofredoc** [comment]
> Should we use a gemfile? (this comment should have been on the recipe CL, but I just thought of it now). With rubygems, if you don't have a `gemfile.lock` file, transitive deps can change, and this broke us once with `fastlane`.
Sure we can, I'll add it to the dependencies module.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
