### PR TITLE
increase the number of shards for web tests

### PR DESCRIPTION
**Pull request by nturgut**
increase the number of shards for web tests on the engine side, this will reduce the flakiness and also reduce the run time for the tests.

### CODE REVIEW

**Review by godofredoc — COMMENTED** [review]
What is the reason for almost doubling the number of shards? this change will most likely affect queue time for everyone.

**Comment by nturgut** [comment]
> What is the reason for almost doubling the number of shards? this change will most likely affect queue time for everyone.

We used to run them with 12 shards on cirrus on framework: https://github.com/Piinks/flutter/blob/6eac4ab3e3335b37e6926c88b40fe5899f153ec3/.cirrus.yml#L225

@yjbanov observed that they are less flaky when they run on more shards.

**Comment by nturgut** [comment]
I stopped running some web tests on unrelated directories, queue time should reduce a bit, at least for the try bots: https://github.com/flutter/engine/pull/21613

**Comment by godofredoc** [comment]
> > What is the reason for almost doubling the number of shards? this change will most likely affect queue time for everyone.
> 
> We used to run them with 12 shards on cirrus on framework: https://github.com/Piinks/flutter/blob/6eac4ab3e3335b37e6926c88b40fe5899f153ec3/.cirrus.yml#L225
> 
> @yjbanov observed that they are less flaky when they run on more shards.

I wouldn't suggest going back to 12 shards without knowing for sure the flakiness is being caused by lack of CPU and/or memory.  The LUCI machines have 4X cpus and memory from the ones that were being used in Cirrus at that time.

**Comment by nturgut** [comment]
> > > What is the reason for almost doubling the number of shards? this change will most likely affect queue time for everyone.
> > 
> > 
> > We used to run them with 12 shards on cirrus on framework: https://github.com/Piinks/flutter/blob/6eac4ab3e3335b37e6926c88b40fe5899f153ec3/.cirrus.yml#L225
> > @yjbanov observed that they are less flaky when they run on more shards.
> 
> I wouldn't suggest going back to 12 shards without knowing for sure the flakiness is being caused by lack of CPU and/or memory. The LUCI machines have 4X cpus and memory from the ones that were being used in Cirrus at that time.

@yjbanov do you have any records from the time these tests first started to create flakes. Does the Chrome synchronization issue related to number of tests running on one shard or to hardware constraints?

**Comment by nturgut** [comment]
I'm closing this issue since @yjbanov added another workaround for the web_tests flakiness. https://github.com/flutter/flutter/pull/67466

**Pull request closed without merging**
