### PR TITLE
Remove tool_general_tests and tool_command_tests builders

### PR DESCRIPTION
**Pull request by jmagman**
Revert part of https://github.com/flutter/infra/pull/339.

Evidently `shard` properties without `subshards` crash.  https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/shard_util/api.py#26
```
Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/engine.py", line 571, in run_steps
    raw_result = recipe_obj.run_steps(api, engine)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/recipe_deps.py", line 832, in run_steps
    properties_def, api=api)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 89, in invoke_with_properties
    arg_names, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/internal/property_invoker.py", line 52, in _invoke_with_properties
    return callable_obj(*props, **additional_args)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipes/flutter/flutter.py", line 36, in RunSteps
    builds = api.shard_util.schedule_builds()
  File "/b/s/w/ir/kitchen-checkout/recipe_engine/recipe_engine/recipe_api.py", line 597, in _inner
    return func(*a, **kw)
  File "/b/s/w/ir/kitchen-checkout/flutter/recipe_modules/shard_util/api.py", line 26, in schedule_builds
    for subshard in self.m.properties.get('subshards'):
TypeError: 'NoneType' object is not iterable
```

Keep the [`tool_integration_tests` tests since those are subsharded and pass](https://ci.chromium.org/p/flutter/builders/try/Linux%20tool_integration_tests/1?).  Remove un-subsharded `tool_general_tests` and `tool_command_tests`.  Make tool_tests only support `general` and `commands`.

Note this will temporarily mean tool_tests integration subshards won't run until https://github.com/flutter/flutter/pull/75171 merges.

### CODE REVIEW

**Review by godofredoc — APPROVED** [review]

**Comment by jmagman** [comment]
```
CRITICAL: projects/flutter: cr-buildbucket.cfg: Error during external validation: Net error: Failed to call https://beefy-dot-cr-buildbucket.appspot.com/_ah/api/config/v1/validate after 4 attempts
```
?

**Comment by jmagman** [comment]
`lucicfg validate ./config/main.star` passes on my machine, the `validate_config` error looks like a network issue?

**Comment by godofredoc** [comment]
> g validate ./config/main.

That error probably means that configurations changed and we can not revert cleanly.

**Comment by jmagman** [comment]
I see this networking issue also reported on the LUCI users chat, they have a backend log full of 503s.  Going to merge this on red since I verified the config is actually valid.

**Comment by godofredoc** [comment]
> I see this networking issue also reported on the LUCI users chat, they have a backend log full of 503s. Going to merge this on red since I verified the config is actually valid.

SGTM.

**Comment by jmagman** [comment]
> I see this networking issue also reported on the LUCI users chat, they have a backend log full of 503s. Going to merge this on red since I verified the config is actually valid.

`validate_config` passed on master: https://cirrus-ci.com/task/5109343358025728

**Pull request merged**
